[project]
name = "nope_nerfacto"
version = "0.1.1"

[tool.setuptools.packages.find]
include = ["nope_nerfacto*"]


[project.entry-points.'nerfstudio.method_configs']
nope-nerfacto = 'nope_nerfacto.nope_nerfacto_configs:nope_nerfacto'
